[package]
name = "icedtea-shell"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
icedtea-contract = { path = "../contract" }
icedtea-ui = { path = "../ui" }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
zbus.workspace = true
async-channel = "2"
crossbeam-channel.workspace = true
futures-util = "0.3"
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
icedtea-harness = { path = "../harness" }
icedtea-clipboard = { path = "../clipboard" }
