[package]
name = "icedtea-settings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "icedtea-settings"
path = "src/main.rs"

[dependencies]
icedtea-config = { path = "../config" }
icedtea-contract = { path = "../contract" }
icedtea-ui = { path = "../ui" }
skia-rs-safe = { version = "0.4.0", default-features = false, features = [
    "std",
] }
crossbeam-channel.workspace = true
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
rustix = "1"
async-channel = "2"
zbus.workspace = true
futures-util = "0.3"
redb.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
xkbcommon = "0.9"

[dev-dependencies]
icedtea-harness = { path = "../harness" }
tempfile = "3"
